name: jaguar_serializer_mongo
description: MongoDB serializer helpers for jaguar_serializer
version: 0.1.0
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_serializer_mongo

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  mongo_dart: ">=0.2.10 <0.3.0"
  jaguar_serializer: ">=0.4.2 <0.5.0"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
